services:
  _defaults:
    autowire: true
    autoconfigure: true

  JvH\JvHIsotopeStockBundle\Controller\BookingController: ~
  JvH\JvHIsotopeStockBundle\EventListener\BookingListener: ~
  JvH\JvHIsotopeStockBundle\Cron\CheckBookingEvents: ~